### ISSUE TITLE
API key badRequest

### ISSUE THREAD

**Issue by sova** [billwinkler/google-translate#1]
Hi, thanks for making this wrapper.  I'm a bit confused on what the {:api-key ""} map ought to look like.  

`{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "API key not valid. Please pass a valid API key.",
    "reason" : "badRequest"
  } ],
  "message" : "API key not valid. Please pass a valid API key.",
  "status" : "INVALID_ARGUMENT"
}`

for `{:api-key ""} ` do I place the whole string including the bookend phrases ----BEGIN PRIVATE KEY--- and ---END PRIVATE KEY--- ?

**Comment by sova** [comment]
Hi, I ended up generating a New API key by searching "credentials" and clicking the + API Key at the top of the page.  It's actually a fairly short key.  Resolved x)

**Comment by billwinkler** [comment]
Hi, it will look something like this...

{:api-key "AIaxYsCxIcI6jtExgnepezaSyjtEgnxtzM7XWsc"}

See https://cloud.google.com/docs/authentication/api-keys for how to
generate an API key.

Bill

**Comment by billwinkler** [comment]
Good deal!
