### ISSUE TITLE
Hide Warnings?

### ISSUE THREAD

**Issue by sova** [billwinkler/google-translate#2]
Hi again! 
Great wrapper.

Hey uh, is there a way to hide the Google Translate warnings on using :api-key instead of the credentials.json file?

`com.google.cloud.translate.TranslateOptions <init>
WARNING: Ignoring Application Default Credentials GOOGLE_APPLICATION_CREDENTIALS: using explicit setting for API key instead.`

I tried searching the clojure-sphere for such a way, still not sure if I can hide this.  Or ought I just ignore this and try and extract the right info from it in a more hacky way?

**Comment by billwinkler** [comment]
Hi, glad to hear that you find it useful.

I’ve also tried to suppress those, but so far no luck.

**Comment by sova** [comment]
Ah, right on.  Thanks for the update.  I will do some snooping.  I think there might be a way to disable the logging via the Google API console but I'm not sure.

**Comment by sova** [comment]
Rather than use `{:api-key "84518642751860865712"}` that sets the key manually I finally caved and used their recommended `export GOOGLE_APPLICATION_CREDENTIALS="path-to-creds.json"` and the warnings disappeared.  So, there's that in case anyone else needs it.
